[package]
name = "axusb_host"
version = "0.1.0"
authors = ["dbydd <dbydd@outlook.com>"]
edition = "2021"

[features]
default = ["backend-xhci","packed-drivers"]

packed-drivers = ["axhid"]
cotton-frontend=["cotton-usb-host"]
backend-xhci = ["xhci"]
parallel = []

[dependencies]
xhci = {version="0.9",optional=true}
axhid = {git = "https://github.com/arceos-usb/axhid.git",optional = true}
usb-descriptor-decoder = {git="https://github.com/arceos-usb/usb-descriptor-decoder-rs.git"}
cotton-usb-host = {version = "0.1.0",optional = true,default-features = false}

tock-registers = "0.9.0"
bit_field = "0.10"
num-derive = "0.4.0"
num-traits = { version = "0.2.16", default-features = false }
byteorder = { version = "1.4.3", default-features = false }
log="0.4"
embassy-futures = "0.1.1"
ringbuf = {version = "0.4.7",default-features = false,features = ["alloc"]}
async-ringbuf = {version = "0.3.1",default-features = false,features = ["alloc"]}
async-lock = {version = "3.4.0",default-features =  false}
futures = {version = "0.3.31",default-features = false,features = ["async-await","alloc"]}
