[package]
name = "axusb_host"
version = "0.1.0"
authors = ["dbydd <dbydd@outlook.com>"]
edition = "2021"

[features]
default = ["backend-xhci","packed-drivers"]

packed-drivers = ["axhid"]
cotton-frontend=["cotton-usb-host"]
backend-xhci = ["xhci"]
parallel = []
trace_xhci_enque_trb=[]
# arceos-pci-xhci = ["pci_types","driver_common","axhal","axalloc"]

[dependencies]
xhci = { git = "https://github.com/dbydd/xhci.git" ,optional = true}
axhid = {git = "https://github.com/arceos-usb/axhid.git",optional = true}
usb-descriptor-decoder = {git="https://github.com/arceos-usb/usb-descriptor-decoder-rs.git"}
cotton-usb-host = {version = "0.1.0",optional = true,default-features = false}

tock-registers = "0.9.0"
bit_field = "0.10"
num-derive = "0.4.0"
num-traits = { version = "0.2.16", default-features = false } #had bug on latest version while use no_std
byteorder = { version = "1.4.3", default-features = false }
log="0.4"
embassy-futures = "0.1.1"
ringbuf = {version = "0.4.7",default-features = false,features = ["alloc"]}
async-ringbuf = {version = "0.3.1",default-features = false,features = ["alloc"]}
async-lock = {version = "3.4.0",default-features =  false}
futures = {version = "0.3.31",default-features = false,features = ["async-await","alloc"]}
match_cfg = "0.1.0"
async-trait = "0.1.85"
lazy_static = "1.5.0"
squeak = "0.2.0"
nosy = {version = "0.1.0",default-features = false,features = ["async"]}

# #arceos
# pci_types = { version = "0.6", optional = true }
# driver_common = { path = "../../arceos_experiment/crates/driver_common" ,optional = true}
# axhal = { path = "../../arceos_experiment/modules/axhal", features = ["irq"] ,optional = true}
# axalloc = { path = "../../arceos_experiment/modules/axalloc" ,optional = true}
