[package]
name = "axusb_host"
version = "0.1.0"
authors = ["dbydd <dbydd@outlook.com>"]
edition = "2021"

[features]
default = ["backend-xhci","packed-drivers"]

packed-drivers = ["axhid"]
cotton-frontend=["cotton-usb-host"]
backend-xhci = ["xhci"]

[dependencies]
tock-registers = "0.9.0"
bit_field = "0.10"
num-derive = "0.4.0"
num-traits = { version = "0.2.16", default-features = false }
byteorder = { version = "1.4.3", default-features = false }
log="0.4"

xhci = {version="0.9",optional=true}
axhid = {git = "https://github.com/arceos-usb/axhid.git",optional = true}
cotton-usb-host = {version = "0.1.0",optional = true,default-features = false}